CREATE TABLE `playlist` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `type` varchar(255) DEFAULT NULL,
  `devicename` varchar(255) DEFAULT NULL,
  `label` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `videolayer` varchar(255) DEFAULT NULL,
  `delay` varchar(255) DEFAULT NULL,
  `allowgpi` varchar(255) DEFAULT NULL,
  `allowremotetriggering` varchar(255) DEFAULT NULL,
  `remotetriggerid` varchar(255) DEFAULT NULL,
  `storyid` varchar(255) DEFAULT NULL,
  `transition` varchar(255) DEFAULT NULL,
  `transitionDuration` varchar(255) DEFAULT NULL,
  `tween` varchar(255) DEFAULT NULL,
  `direction` varchar(255) DEFAULT NULL,
  `seek` varchar(255) DEFAULT NULL,
  `length` varchar(255) DEFAULT NULL,
  `freezeonload` varchar(255) DEFAULT NULL,
  `triggeronnext` varchar(255) DEFAULT NULL,
  `autoplay` varchar(255) DEFAULT NULL,
  `color` varchar(255) DEFAULT NULL,
  `timecode` varchar(255) DEFAULT NULL,
  `starttime` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `pushtime` datetime(2) DEFAULT NULL,
  `duration` varchar(255) DEFAULT NULL,
  `useauto` varchar(255) DEFAULT NULL,
  `commercial` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=40 DEFAULT CHARSET=utf8;